### ISSUE TITLE
node 5 and babel 6

### ISSUE THREAD

**Issue by olegakbarov** [mesosphere/reactjs-components#106]
Are you interested in PR with upgrade of both to latest Node and Babel?

**Comment by rcorral** [comment]
We are and it is in our roadmap, but at the moment we aren't ready for this change just yet to be merged into master.
Do you know how much work is involved for this? And what changes are required?

**Comment by olegakbarov** [comment]
I actually already made it locally (that includes `eslint 1.0.0`, `babel 6.3.13`, `react 0.14.3`, `jest-cli 0.8.0` and also i run it on node 5.1.1), however this breaks some tests (react 0.14 do have breaking changes), and i need time to fix it up.

That might feel a little excessive, but this dependencies are quite tightly coupled so it feels natural for me to update them it one batch. 

Moreover i've added a few more rules to `.eslintrc`, and forced myself to refactor a little bit. 

I do understand that this might not fit in your plan, but how about i complete this and you'll take a look?

**Comment by rcorral** [comment]
Sounds good. We certainly want to do this. So one option is for you to have it done and we merge this in when ready.
It would be nice if we could do the eslint changes separately and others if possible.

**Comment by rcorral** [comment]
This has been completed.
