### ISSUE TITLE
Scrollbar is visible

### ISSUE THREAD

**Issue by aldipower** [mesosphere/reactjs-components#220]
I see a scrollbar at the confirm dialog. I think it shouldn't be there.

![confirm](https://cloud.githubusercontent.com/assets/859154/13849322/f5254a62-ec55-11e5-8f2c-f2280cb17a07.png)

Firefox 39, Linux

**Comment by weblancaster** [comment]
closing outdated/old issue because this is probably fixed (and not followed anymore).
