### ISSUE TITLE
Allow react 15.4.x as a peer dep

### ISSUE THREAD

**Issue by nLight** [mesosphere/reactjs-components#385]
Something like this would be awesome! Tried to cook a PR but realized that I need some on-boarding here.
```
"react": "^0.14.0 || ^15.0.0-0 || ^15.4.0-0",
"react-addons-css-transition-group": "^0.14.0 || ^15.0.0-0 || ^15.4.0-0",
```

@jfurrow 🙇

**Comment by jfurrow** [comment]
Sorry @nLight for the delay! I will look into this!
