### ISSUE TITLE
Quesiton: can we use these components in ReactJS 15 application?

### ISSUE THREAD

**Issue by RupenAnjaria** [mesosphere/reactjs-components#437]
Is this running on ReactJS 16? if so, can we use these components in a ReactJS 15 application?

**Comment by nLight** [comment]
Hey @RupenAnjaria! We're using the components in a react@15 app https://github.com/dcos/dcos-ui
The full testing matrix can be found here https://github.com/mesosphere/reactjs-components/blob/master/.travis.yml
